service: device-service
provider:
  name: aws
  stage: ${opt:stage, "dev"}
  runtime: go1.x
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/RackOrganizer
    - Effect: Allow
      Action:
      - s3:GetObject
      - s3:PutObject
      - s3:PutObjectAcl
      Resource: "*"

package:
  individually: true
  exclude:
    - "*/**"

functions:
  device:
      handler: lambda/http/bin/main
      events:
          - http:
              method: GET
              path: device
          - http:
              method: GET
              path: device/{deviceId}
          - http:
              method: PUT
              path: device/{deviceId}
              authorizer:
                arn: ${cf:user-service-${self:provider.stage}.AuthorizerLambda}
                resultTtlInSeconds: 0
      package:
          include:
            - lambda/http/bin/main
