service: device-service
provider:
  name: aws
  runtime: go1.x
  region: eu-west-1

package:
  individually: true
  exclude:
    - "*/**"

functions:
  device:
      handler: lambda/http/bin/main
      events:
          - http:
              method: GET
              path: device
          - http:
              method: PUT
              path: device/{deviceId}
      package:
          include:
            - lambda/http/bin/main
